QuanLySinhVien/QuanLySinhVien/Controllers/lophocsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuanLySinhVien.Models;

namespace QuanLySinhVien.Controllers
{
    public class lophocsController : Controller
    {
        private DBContext db = new DBContext();

        // GET: lophocs
        public ActionResult Index()
        {
            
            return View(db.lophocs.ToList());
        }

        // GET: lophocs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            lophoc lophoc = db.lophocs.Find(id);
            if (lophoc == null)
            {
                return HttpNotFound();
            }
            return View(lophoc);
        }
        public ActionResult GiangVien()
        {
            return View(db.giangviens.ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuanLySinhVien/QuanLySinhVien/Controllers/sinhviensController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuanLySinhVien.Models;

namespace QuanLySinhVien.Controllers
{
    public class sinhviensController : Controller
    {
        private DBContext db = new DBContext();

        // GET: sinhviens
        public ActionResult Index()
        {
            taikhoan taikhoan = (taikhoan)Session["taikhoan"];
            if (taikhoan == null)
            {
                return Redirect("/DangNhap/DangNhap");
            }

            return View(db.sinhviens.ToList());
        }
        public ActionResult TimKiem(string key)
        {
            if (string.IsNullOrEmpty(key))
            {
                return View("Index");
            }
            else
            {
                var lisv = db.sinhviens.Where(sv => sv.maSV.ToString().Contains(key) || sv.hoTen.Contains(key)||sv.tenDangNhap.Contains(key)).ToList();
                return View(lisv);
            }

        }
        // GET: sinhviens/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            sinhvien sinhvien = db.sinhviens.Find(id);
            if (sinhvien == null)
            {
                return HttpNotFound();
            }
            return View(sinhvien);
        }
        [HttpGet]
        public ActionResult Create()
        {
            try
            {
                ViewBag.maLop = new SelectList(db.lophocs, "maLop", "tenLop");
                return View();
            }
            catch (Exception e)
            {
                // Log the error message
                ViewBag.err = "Error loading form: " + e.Message;
                return View("Error");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "maSV, maLop,hoTen,diachi,sdt,email,diemTX1,diemXT2,diemThi")] sinhvien sinhvien)
        {
            try
            {
                sinhvien.hinhAnh = "";
                var f = Request.Files["ImageFile"];
                if (f != null && f.ContentLength > 0)
                {
                    string fileName = Path.GetFileName(f.FileName);
                    string uploadPath = Server.MapPath("~/Content/Images/" + fileName);
                    f.SaveAs(uploadPath);
                    sinhvien.hinhAnh = fileName;
                }
                else
                {
                    ViewBag.Error = "Ảnh không được bỏ trống!";
                }

                var lastStudent = db.sinhviens.OrderByDescending(s => s.maSV).FirstOrDefault();
                int newStudentId = lastStudent != null ? lastStudent.maSV : 1;
                do
                {
                    newStudentId ++;
                    
                } while (db.sinhviens.Any(t => t.maSV == newStudentId));
                sinhvien.maSV = newStudentId;

                sinhvien.tenDangNhap = "2024SV00" + newStudentId;

                // Tạo tài khoản mới
                taikhoan tk = new taikhoan()
                {
                    tenDangNhap = sinhvien.tenDangNhap,
                    matkhau = "abc123"
                };
                db.taikhoans.Add(tk);

                // Thêm sinh viên vào cơ sở dữ liệu
                db.sinhviens.Add(sinhvien);
                db.SaveChanges();

                ViewBag.Error = "Thêm mới thành công!";
                ViewBag.maLop = new SelectList(db.lophocs, "maLop", "tenLop", sinhvien.maLop);
                return View();
            }
            catch (Exception e)
            {
                ViewBag.Error = sinhvien.maSV;
                ViewBag.Error = "Có lỗi: " + e.Message;
                if (e.InnerException != null)
                ViewBag.Error += e.InnerException.ToString();
                ViewBag.maLop = new SelectList(db.lophocs, "maLop", "tenLop", sinhvien.maLop);

                return View(sinhvien);
            }
        }



        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            sinhvien sinhvien = db.sinhviens.Find(id);
            if (sinhvien == null)
            {
                return HttpNotFound();
            }

            ViewBag.maLop = new SelectList(db.lophocs, "maLop", "tenLop", sinhvien.maLop);
            return View(sinhvien);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(sinhvien sv)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var f = Request.Files["ImageFile"];
                    if (f != null && f.ContentLength > 0)
                    {
                        string fileName = Path.GetFileName(f.FileName);
                        string uploadPath = Server.MapPath("~/Content/Images/" + fileName);
                        f.SaveAs(uploadPath);
                        sv.hinhAnh = fileName;
                    }
                    else
                    {
                        sv.hinhAnh = Request.Form["hinhAnh"];
                    }

                    db.Entry(sv).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Có lỗi: " + ex.Message;

            }
            ViewBag.maLop = new SelectList(db.lophocs, "maLop", "tenLop", sv.maLop);
            return View(sv);
        }
        [HttpPost]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            sinhvien sinhvien = db.sinhviens.Find(id);
            if (sinhvien == null)
            {
                return HttpNotFound();
            }
            else
            {
                db.sinhviens.Remove(sinhvien);
                db.SaveChanges();
                TempData["DeleteSuccess"] = true;
            }

            return RedirectToAction("Index");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuanLySinhVien/QuanLySinhVien/Views/Shared/_Layout.cshtml
@using QuanLySinhVien.Models
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        .table th {
            background-color: lightblue;
        }
        /* Kiểu cho các mục dropdown */
        .dropdown {
            position: relative;
            display: inline-block;
        }

        /* Kiểu cho menu dropdown */
        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
            border-radius: 6px;
        }

            /* Kiểu cho các mục trong menu dropdown */
            .dropdown-content a {
                color: black;
                margin: 0;
                padding: 10px;
                width: 200px;
                text-decoration: none;
                display: block;
                text-align: left;
            }

        /* Hiển thị menu dropdown khi di chuột vào */
        .dropdown:hover .dropdown-content {
            display: block;
        }

        /* Hiển thị submenu khi di chuột vào mục con */
        .dropdown-submenu:hover .dropdown-content {
            display: block;
            left: 100%;
            top: 0;
        }

        /* Đảm bảo submenu nằm ngang bên phải của mục chính */
        .dropdown-submenu {
            position: relative;
        }
        .navbar a{
            color: darkblue;
        }
        .navbar a:hover, .dropdown:hover .dropbtn {
            color: orange;
        }

        .dropdown-content a:hover {
            text-decoration: underline;
        }
        footer{
            position: fixed;
            bottom: 0;
            width: 100%;
        }
        footer p {
            font-size: 15px;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm " style="background-color: darkblue">
        <div class="container">
            <ul class="navbar-nav text-black w-100 d-flex justify-content-between align-items-center">
                <li class="nav-item">
                    <a href="@Url.Action("Index", "sinhviens")">
                        <img src="~/Content/Images/logo-haui.png" width="60" style="margin-right: 10px;" />
                    </a>
                </li>
                <li class="nav-item"><b><a href="@Url.Action("Index", "sinhviens")" class="nav-link" style="color: white; font-size: 25px">QUẢN LÝ SINH VIÊN</a></b></li>
                <li class="nav-item flex-grow-1 d-flex justify-content-center">
                    @using (Html.BeginForm("TimKiem", "sinhviens", FormMethod.Post))
                    {
                        <div class="justify-content-xxl-center">
                            <input type="text" name="key" style="width:580px ;background-color: beige; border-radius: 50px; border-color: white; padding:3px 10px;" placeholder="Nhập từ khóa ...">
                            <input type="submit" style="background-color: #0FC2C2; color: white; font-weight: bold; border-radius: 50px; width: 100px; border-color: white" value="Tìm kiếm" />

                        </div>
                    }

                </li>
            </ul>
        </div>
    </nav>

    <nav class="navbar navbar-expand-sm navbar-toggleable-sm ">
        <div class="container">
            <ul class="navbar-nav d-flex justify-content-center w-100 fw-bold text-black">
                <li style="margin: 0px 10px">@Html.ActionLink("Sinh viên", "Index", "sinhviens", new { area = "" }, new { @class = "nav-link" }) </li>
                <li style="margin-top: 5px">&nbsp;|&nbsp;</li>
                <li style="margin: 0px 10px">@Html.ActionLink("Lớp học", "Index", "lophocs", new { area = "" }, new { @class = "nav-link" }) </li>
                <li style="margin-top: 5px">&nbsp;|&nbsp;</li>
                <li style="margin: 0px 10px">@Html.ActionLink("Giảng viên", "GiangVien", "lophocs", new { area = "" }, new { @class = "nav-link" })</li>
                <li style="margin-top: 5px">&nbsp;|&nbsp;</li>
                @{
                    if (Session["taikhoan"] == null)
                    {
                        <li style="margin: 0px 10px">@Html.ActionLink("Đăng nhập", "DangNhap", "DangNhap", new { area = "" }, new { @class = "nav-link" })</li>

                    }
                    else
                    {
                        DBContext db = new DBContext();
                        taikhoan tk = (taikhoan)Session["taikhoan"];
                        giangvien gv = db.giangviens.FirstOrDefault(m => m.tenDangNhap == tk.tenDangNhap);
                        <li style="margin: 0 10px" class="nav-item">
                            <div class="dropdown">
                                <a href="#" class="dropbtn nav-link" style="color: orange;">@gv.hoTen</a>
                                <div class="dropdown-content">
                                    <a href="@Url.Action("DangXuat", "DangNhap")">Đăng xuất</a>
                                    <a href="@Url.Action("TaiKhoanCuaToi", "DangNhap")">Tài khoản của tôi</a>
                                </div>
                            </div>
                        </li>

                    }


                }

            </ul>
        </div>
    </nav>
    <div class="container body-content" style="padding: 2px">
        @RenderBody()
        <hr />

    </div>
    <footer class="justify-content-center mt-5" style="background-color: #E0E5F2; padding: 20px 0 0 0; margin-bottom:-17px">
        <div style="text-align:center;">
            <p style="font-size:12px"><i>&copy; @DateTime.Now.Year - My Student Management Application</i></p>
        </div>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>